"""add_codigo_to_turma

Revision ID: 06638f983323
Revises: b34b9d6f03da
Create Date: 2026-07-07 15:45:06.698431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06638f983323'
down_revision: Union[str, Sequence[str], None] = 'b34b9d6f03da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turmas', sa.Column('codigo', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_turmas_codigo'), 'turmas', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turmas_codigo'), table_name='turmas')
    op.drop_column('turmas', 'codigo')
    # ### end Alembic commands ###
